### PR TITLE
Support for ContentEncoding

### PR DESCRIPTION
**Pull request by dvonlehman**
Hi, I need the ability to store gzip encoded files in S3rver. The real S3 handles this with the ContentEncoding parameter on the [putObject command](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property).  The PR includes code to read/write a contentEncoding key in the metadata file. Also I moved the functionality to create the test buckets into the mocha before block so it's possible to run one test at a time and have the test buckets exist. Added a new unit test for storing and reading a gzipped copy of jquery. All tests are passing when running `npm test`.

### CODE REVIEW

**Comment by jamhall** [comment]
Hi @dvonlehman 

Thank you for your contribution!  A nice extra feature.

I've merged your pull request.

**Comment by jamhall** [comment]
Would you like me to create a new release?

**Comment by dvonlehman** [comment]
A new release to npm would be great. Thanks.

**Comment by jamhall** [comment]
Released a new version. Sorry for the delay; it completely slipped my mind.

Version is now: 0.0.5

Thanks for your contributions.

**Pull request merged**
