### PR TITLE
Prettier v2 formatting changes

### PR DESCRIPTION
**Pull request by leontastic**
This PR is the result of running `npm run prettier -- --write` after merging #606

Might need to test this against upgraded eslint dependencies too

### CODE REVIEW

**Comment by ad-m** [comment]
We must carefully merge it, because it will create conflicts with all existing PR.

**Comment by leontastic** [comment]
> We must carefully merge it, because it will create conflicts with all existing PR.

Good point, I'll make sure to put this in after dealing with the existing PRs.

**Comment by leontastic** [comment]
Use `git commit --no-verify` if you want to avoid `husky` polluting your own commits with these lint fixes. Would probably result in nicer PRs if put it in before this one is merged.

**Review by kherock — APPROVED** [review]
With the exception of your PR at #682, all existing PRs either don't have significant code changes or already have merge conflicts. ln the interest of getting checks passing, I'll merge this soon if there aren't any objections.

**Review by ad-m — APPROVED** [review]

**Comment by leontastic** [comment]
Going to merge this now it looks like PR activity has subsided. Merging formatting changes now prevents them from polluting future diffs due to lint-staged, I found that annoying when I was working on other stuff.

**Pull request merged**
