### PR TITLE
Optimise the loading of the home page (root)

### PR DESCRIPTION
**Pull request by DavidBeale**
Hi,

This is an optimisation for serving the home page of a static site. Stops the whole bucket contents being read and parsed.

thanks,
    David

### CODE REVIEW

**Comment by jamhall** [comment]
Mered :-) Thanks!

Quick question: What are you using s3rver for? Thanks!

**Comment by DavidBeale** [comment]
I am building a site which deploys to S3, and I am using s3rver for a local dev server.

**Comment by jamhall** [comment]
Excellent. Thanks for your contributions. I've just pushed another commit (formatted and linted files). :-)

**Comment by DavidBeale** [comment]
Thanks

**Comment by DavidBeale** [comment]
Would you mind pushing a new release, thanks.

**Comment by jamhall** [comment]
Done! Sorry for the delay. Cheers.

**Comment by DavidBeale** [comment]
Np. Thanks

**Pull request merged**
