### PR TITLE
S3Event's eventTime should always be a new date

### PR DESCRIPTION
**Pull request by nschirmer**
It should not rely on the object's creation date, especially since that value never exists in S3rver.

### CODE REVIEW

**Comment by nschirmer** [comment]
@specialkk I closed the last PR and opened this new one for the eventTime fix.

**Comment by specialkk** [comment]
Thanks, I can take it from here - I still want to remove that unnecessary getter and add a test case.

**Comment by nschirmer** [comment]
Thanks @specialkk! Cheers.

**Comment by nschirmer** [comment]
@specialkk which version tag will this show up in? 2.2.5 or will you publish another?

**Comment by specialkk** [comment]
@leontastic is in charge of publishing to npm, it should be v2.2.6 when it's up.

**Comment by nschirmer** [comment]
Hi @leontastic, any chance you could publish 2.2.6 tag soon? I need to coordinate with the serverless-s3-local package afterwards to get them to reference the new version so that this fix ultimately makes its way to my project.

Thank you!

**Comment by leontastic** [comment]
Hi @nschirmer, my sincere apologies for being AWOL from Github recently. I have published v2.2.6. Thank you for your contribution!

**Pull request merged**
