### PR TITLE
Correct expirestime calculation

### PR DESCRIPTION
**Pull request by SangMo93**

### CODE REVIEW

**Comment by SangMo93** [comment]
anybody check something? or Feedback?

**Comment by SangMo93** [comment]
if do not change calculation. presigned url immediately expires when I request presigned url.
expires time and request time are same! so you don't access presigend url

**Comment by kherock** [comment]
Hi, thanks so much for the PR! Sorry I wasn't able to address this before I went on vacation. This looks good as-is, I'll try to publish a patch release this weekend.

**Comment by kherock** [comment]
Thanks for your patience, this is now released in v3.3.0.

**Pull request merged**
