### PR TITLE
fixing issue #15 - support AmazonS3Client.listObjects by fixing wrong XML element

### PR DESCRIPTION
**Pull request by ranwasserman**
fixing issue #15

### CODE REVIEW

**Comment by jamhall** [comment]
Excellent. Thank you for your contribution :)

**Comment by ranwasserman** [comment]
Sure, Thank you!
could you please push it to npm?

**Comment by jamhall** [comment]
@ranwasserman  Yups....I'll do it now.

**Comment by jamhall** [comment]
Done! 

- v0.0.9 has been [released](https://github.com/jamhall/s3rver/releases/tag/v0.0.9)
- NPM has been updated -  https://www.npmjs.com/package/s3rver

Cheers!

**Comment by ranwasserman** [comment]
Awesome!

**Pull request merged**
