### PR TITLE
Remove duplicate code for save content in store

### PR DESCRIPTION
**Pull request by ad-m**
I have notice some code duplicated, so I suggest extract helper method in store for that.

### CODE REVIEW

**Comment by ad-m** [comment]
Taking into account previous runs eg. https://github.com/jamhall/s3rver/runs/3707557361?check_suite_focus=true that failure looks as tests flakiness.

**Comment by kherock** [comment]
Hey! Thanks for this, there was another PR I just merged that fixes the test flakiness on Windows. It's a regression from dropping fs-extra a while back. It should pass once you rebase your branch.

**Comment by ad-m** [comment]
The PR has been rebased. 

It seems to me that the decrase in test coverage is not in line with this change, which limits code inflation.

**Comment by kherock** [comment]
Yeah no worries about the coverage, thanks @ad-m!

**Pull request merged**
