### PR TITLE
Fixes #223

### LINKED ISSUE #223: Sending empty list of objects with s3.deleteObjects causes a crash.
Hi! Following code will result an error: 

```javascript
s3.deleteObjects(
        {
          Bucket: config.BUCKET_NAME,
          Delete: {
            Objects: []
          }
        }
      );
```

Causes: 

```
Uncaught TypeError: Cannot read property 'map' of undefined
      at xml2js.parseString (node_modules/s3rver/lib/controllers.js:114:45)
      at Parser.<anonymous> (node_modules/xml2js/lib/xml2js.js:489:18)
      at Parser.emit (domain.js:421:20)
      at SAXParser.onclosetag (node_modules/xml2js/lib/xml2js.js:447:26)
      at emit (node_modules/sax/lib/sax.js:640:35)
      at emitNode (node_modules/sax/lib/sax.js:645:5)
      at closeTag (node_modules/sax/lib/sax.js:905:7)
      at SAXParser.write (node_modules/sax/lib/sax.js:1306:13)
      at Parser.exports.Parser.Parser.parseString (node_modules/xml2js/lib/xml2js.js:508:31)
      at Parser.parseString (node_modules/xml2js/lib/xml2js.js:7:59)
      at Object.exports.parseString (node_modules/xml2js/lib/xml2js.js:540:19)
      at deleteObjects (node_modules/s3rver/lib/controllers.js:113:12)
      at req.pipe.data (node_modules/s3rver/lib/controllers.js:517:13)
      at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:36:43)
      at ConcatStream.emit (domain.js:421:20)
      at finishMaybe (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:620:14)
      at afterWrite (node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:482:3)
      at process._tickCallback (internal/process/next_tick.js:114:19)
```

### PR DESCRIPTION
**Pull request by n1ru4l**

### CODE REVIEW

**Comment by n1ru4l** [comment]
@leontastic Could you please publish a new release? I already did the release draft.

**Comment by specialkk** [comment]
Do we want to include #222 and #226 in the release too?

**Comment by n1ru4l** [comment]
@specialkk done

**Comment by leontastic** [comment]
@n1ru4l released v2.2.4

**Pull request merged**
