### PR TITLE
Changed fast-xml-parser version and implementation

### PR DESCRIPTION
**Pull request by miguel-padilla92**

### CODE REVIEW

**Review by j0k3r — APPROVED** [review]

**Comment by zachrog** [comment]
Nice job. Would love to get this merged in ASAP to fix the high security vulnerability that appears when using S3rver as a dependency.

**Comment by j0k3r** [comment]
After checking it, there are really more stuff to be done before that PR will be ok to merge.

I've forked the project to fix them all.

https://github.com/20minutes/s3rver/pull/1

**Comment by miguel-padilla92** [comment]
> After checking it, there are really more stuff to be done before that PR will be ok to merge.
> 
> I've forked the project to fix them all.
> 
> [20minutes#1](https://github.com/20minutes/s3rver/pull/1)

I saw the PR you made, will you do a merge so I can close this one?

**Comment by j0k3r** [comment]
I'm not sure @jamhall is actively maintaining the lib, so we'll keep using our fork instead of providing a PR here unless @jamhall wants to integrate it.

**Comment by zachrog** [comment]
> I'm not sure @jamhall is actively maintaining the lib, so we'll keep using our fork instead of providing a PR here unless @jamhall wants to integrate it.

Thank you @j0k3r . I think you are correct. We appreciate your work.

**Pull request closed without merging**
