### PR TITLE
Add Upload Part - Copy

### PR DESCRIPTION
**Pull request by juliangruber**
This partially implements [Upload Part - Copy](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPartCopy.html):

- [X] Upload part by copy
- [X] Cross bucket
- [x] `x-amz-copy-source-range`
- [ ] `x-amz-copy-source-if-match`
- [ ] `x-amz-copy-source-if-none-match`
- [ ] `x-amz-copy-source-if-unmodified-since`
- [ ] `x-amz-copy-source-if-modified-since`

This is as much as I personally need from this function.

### CODE REVIEW

**Comment by kherock** [comment]
Thanks for the quick PR! Let me know when you want me to review this.

**Comment by juliangruber** [comment]
I don't need this function any more so I'll let you decide what to do with this :)

**Comment by jeffbski-rga** [comment]
This is still good functionality. I currently need it in my project.

**Review by kherock — APPROVED** [review]
I've improved the tests for this a bit and added support for copy ranges. the `x-amz-copy-source-if-*` headers are still unimplemented but should be straightforward to add later.

**Pull request merged**
